# docker-compose.yml
version: '3.8'

services:
  example-core:
    build: ./example-core
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./example-core/app:/app
    depends_on:
      - dbpubsub
      - localstack

  notification-service:
    build: ./notification-service
    ports:
      - "8001:8001"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./notification-service/app:/app
    depends_on:
      - dbpubsub
      - localstack

  queue-service:
    build: ./queue-service
    ports:
      - "8004:8004"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./queue-service/app:/app
    depends_on:
      - dbpubsub
      - localstack
  
  dbpubsub:
    container_name: "db-pubsub"
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'snsdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./localstack/db-data:/var/lib/mysql


  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-pubsub}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - LS_LOG=info
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack/${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/scripts/aws-startup.sh:/etc/localstack/init/ready.d/init-aws.sh"
    depends_on:
      - dbpubsub